import { describe, expect, it } from 'vitest';
import { BookmarksParseError, parseBookmarks } from '../src/ingest/bookmarks.js';

const EXPORT = `<!DOCTYPE NETSCAPE-Bookmark-file-1>
<!-- This file was generated by feedly -->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarks</TITLE>
<H1>Feedly - Saved For Later</H1>
<DL><p>
  <DT><H3>Feedly - Saved For Later</H3>
    <DL><p>
    <DT><H3>Saved in 2015</H3>
    <DL><p>
      <DT><A HREF="https://example.com/a?x=1&amp;y=2#frag" ADD_DATE="1443166648">Tom &amp; Jerry&rsquo;s   guide</A>
      <DT><A HREF="http://example.com/b" ADD_DATE="1444052830">Second</A>
    </DL><p>
    <DT><H3>Saved in 2016</H3>
    <DL><p>
      <DT><A HREF="https://example.com/a?x=1&amp;y=2" ADD_DATE="1462748104">Repeat of the first</A>
      <DT><A HREF="https://example.com/no-title" ADD_DATE="not-a-number"></A>
      <DT><A HREF="javascript:alert(1)">Script</A>
      <DT><A HREF="ftp://example.com/file">FTP</A>
    </DL><p>
    </DL><p>
</DL><p>`;

describe('parseBookmarks', () => {
  it('reads links from every folder with their title and save date', () => {
    const { bookmarks, invalid, duplicates } = parseBookmarks(EXPORT);
    expect(bookmarks).toEqual([
      {
        url: 'https://example.com/a?x=1&y=2',
        title: 'Tom & Jerry’s guide',
        savedAt: new Date(1443166648_000),
      },
      { url: 'http://example.com/b', title: 'Second', savedAt: new Date(1444052830_000) },
      { url: 'https://example.com/no-title', title: null, savedAt: null },
    ]);
    expect(duplicates).toBe(1);
    expect(invalid).toEqual(['javascript:alert(1)', 'ftp://example.com/file']);
  });

  it('rejects a file without links', () => {
    expect(() => parseBookmarks('<html><body>nothing</body></html>')).toThrow(BookmarksParseError);
  });
});
